baseURL = "https://nicolasmessier1.github.io"
languageCode = "en-EN"
title = "My blog"
theme = "yinyang"
DefaultContentLanguage = "en"

[author]
  name = "Nicolas Messier"
  homepage = "https://nicolasmessier1.github.io/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1

[params]
disqus = "disqus_1K2MfFMIOY" # disqus account name
extraHead = ''
mainSections = ["posts"]

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About"
link = "https://joway.io"
